"""Add relationships between Band, Venue and Concert

Revision ID: 7f50f00c64c0
Revises: fc754fd2a18a
Create Date: 2024-09-18 02:11:02.602142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f50f00c64c0'
down_revision: Union[str, None] = 'fc754fd2a18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
