"""Add many-to-many relationship between Band and Venue through Concert

Revision ID: ecdaa32247dc
Revises: 7f50f00c64c0
Create Date: 2024-09-18 02:27:25.961988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecdaa32247dc'
down_revision: Union[str, None] = '7f50f00c64c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
